name: Label sponsors

on:

  pull_request:

    types: [opened]

  issues:

    types: [opened]

jobs:

  build:

    name: is-sponsor-label

    runs-on: ubuntu-latest

    steps:
      - uses: JasonEtco/is-sponsor-label-action@v1

        with:

          label: Sponsor Request ❤️

        env:

          GITHUB_TOKEN: ${{56aaea9a2df551417fb266679ed25852cbbf81aa }}
